### ISSUE TITLE
[Question] What is the difference between -ncurses and -slang downloads?

### ISSUE THREAD

**Issue by paulvi** [krolig/mc#5]
What is the difference between -ncurses and -slang downloads?

There is no references in README or in https://midnight-commander.org/wiki/Binaries

**Comment by krolig** [comment]
> What is the difference between -ncurses and -slang downloads?

For MC users, the main difference is in the styling of the file panels and dialog boxes.

ncurses - single line frames
slang - double / broken frames

[Example mc with slang](https://api.monosnap.com/file/download?id=5gM3JWKojUSGWVP2SQ3rOOIMB8jhma) (terminal font - Courier New 11pt)

**Comment by robert7** [comment]
Hi,
I installed mc-4.8.25-x86_64-ncurses.dmg (as the newest version 4.8.26 seems to have problem with modified keymap)...

It was weirdly slow...- It had like lag 1-2 seconds to open a dialog (e.g. a Directory HotList)

Then I reinstalled with mc-4.8.25-x86_64-slang.dmg and seems to be OK
(I'm on macOS 11.2.3)

So its seems that the difference is bigger than single/double frames..?

**Comment by krolig** [comment]
Hi, Robert.

This is the first time I meet such a bug with a delay.
It shouldn't be like that.
[Try version 4.8.26](https://github.com/krolig/mc/releases/tag/4.8.26)

**Comment by robert7** [comment]
Hi,
installed the  mc-4.8.26-x86_64-ncurses.dmg, and it has the same problem with "lag".
The "mc-4.8.25-x86_64-slang.dmg" is OK.
Unfortunately 4.8.26 has a bug where modified keymap in ~/.config/mc/mc.keymap is ignored (as it is described in https://www.linuxquestions.org/questions/slackware-14/midnight-commander-4-8-26-keymap-not-working-4175689730/ )

So I need to stay with 4.8.25 "slang".
Unfortunately the "lag" (delay between keypress and dialog display) can't be shown by screen shoots nor video... So I don't know how to demonstrate.
Robert

-------- Forwarded Message --------
Subject:     Re: [krolig/mc] What is the difference between -ncurses and -slang downloads? (#5)
Date:     Fri, 19 Mar 2021 10:37:04 -0700
From:     Kroleg <notifications@github.com>

Hi, Robert.
This is the first time I meet such a bug with a delay.
It shouldn't be like that.
Try version 4.8.26

**Comment by paulvi** [comment]
@robert7 lag issue is not related to this issue, it should have been separate
