### ISSUE TITLE
MC does not appear in programs after installer finishes with success

### ISSUE THREAD

**Issue by paulvi** [krolig/mc#6]
When using installer from mc-4.8.26-x86_64-ncurses.dmg
MC does not appear in programs after installer finishes with success

**Comment by krolig** [comment]
> When using installer from mc-4.8.26-x86_64-ncurses.dmg
> MC does not appear in programs after installer finishes with success

mc is launched from Terminal.app program
"mc" - without quotes.

**Comment by paulvi** [comment]
OK
